# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            Zhao Hua Xi Shi
tagline:          '0111'
description:      '<a href="https://twitter.com/" target="_blank">@Hi</a>.'
baseurl:          '/life'
url:              https://ambuilding.github.io
paginate:            5

# About/contact
author:
  name:           'Wo'
  url:            https://twitter.com/
  email:             explorewo@gmail.com
  repo:           https://github.com/ambuilding

# Custom vars
version:             2.0.0

google_analytics: UA-108096934-1
